colorexperiment_prj/urls.py
from django.conf.urls import url
from django.conf.urls import include
from django.contrib import admin

from django.conf.urls.static import static
from django.conf import settings

from experiment import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name="index"),
    url(r'^stimulus/(?P<stimulus_id>\d+)/$', views.stimulus, name="stimulus"),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^logout/$', views.logout_user, name="logout"),
    url(r'^profile/$', views.profile, name="profile"),
    url(r'^api/submit/$', views.submit, name="submit"),
    url(r'^api/change/user/$', views.change_user, name="change_user"),
    url(r'^api/change/user-info/$', views.change_userinfo, name="change_userinfo"),
    url(r'^excel/(?P<stimulus_id>\d+)/$', views.result, name="result"),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

experiment/models.py
from django.db import models
from django.db.models.signals import pre_delete
from django.dispatch.dispatcher import receiver

from django.contrib.auth.models import User

from PIL import Image as Img
from io import StringIO

# Create your models here.


class UserInfo(models.Model):
    GENDER_CHOISES = (
            (0, u"Мужской"),
            (1, u"Женский"),
            )

    EDU_TYPES_CHOISES = (
            (0, u"Гумaнитарный"),
            (1, u"Технический"),
            )

    EDU_CHOISES = (
            (0, u"Отсутвует"),
            (1, u"Среднее"),
            (2, u"Среднее специальное"),
            (3, u"Высшее профессиональное"),
            )

    ART_CHOISES = (
            (0, u"Нет"),
            (1, u"Да"),
            )
    
    user = models.OneToOneField(User, on_delete=models.CASCADE, default=0)
    gender = models.IntegerField( u"пол", default=0, 
            choices=GENDER_CHOISES )
    age = models.IntegerField( u"возраст", default=0)
    edu_type = models.IntegerField( u"тип образования", 
            default=0, choices=EDU_TYPES_CHOISES )
    edu = models.IntegerField( u"образование", 
            default=0, choices=EDU_CHOISES)
    art_exp = models.IntegerField(u"художественная подготовка",
            default=0, choices=ART_CHOISES)
    edu_prof = models.CharField( u"профиль подготовки", 
            max_length=140)
    phone = models.CharField( u"телефон", max_length=20,
            blank=True, null=True)
    cinema_freq = models.IntegerField( u"частота походов в кинотеатр",
            default=0, help_text="штуки в месяц")
    cinema_genre = models.CharField( u"любимый жанр кино", max_length=140)

    class Meta:
        ordering = ['user']
        verbose_name = u"Профиль"
        verbose_name_plural = u"Профили"

    def __str__(self):
        return "%s %s" % (self.user.last_name, self.user.first_name)


class StimulType(models.Model):
    pos = models.PositiveIntegerField( u"позиция",
            default=0)
    name = models.CharField( u"Название", max_length=50)
    class Meta:
        ordering = ['pos']
        verbose_name = u"Тип стимула"
        verbose_name_plural = u"Типы стимулов"
    
    def __str__(self):
        return self.name

class Stimul(models.Model):
    pos = models.PositiveIntegerField( u"позиция",
            default=0)
    show = models.BooleanField(u"доступен",
            default=True)
    stype =  models.ForeignKey("StimulType", 
            on_delete=models.CASCADE, default=0)
    name = models.CharField( u"Название", max_length=50)

    class Meta:
        ordering = ['show', 'pos']
        verbose_name = u"Стимул"
        verbose_name_plural = u"Стимулы"
    
    def __str__(self):
        status = u"скрыт"
        if self.show:
            status = u"доступен"
        return "%s | %s" % (self.name, status)


class ImageType(models.Model):
    pos = models.PositiveIntegerField( u"позиция",
            default=0)
    name = models.CharField( u"Название", max_length=50)
    class Meta:
        ordering = ['pos']
        verbose_name = u"Тип изображения"
        verbose_name_plural = u"Типы изображений"
    
    def __str__(self):
        return self.name


def image_path(instance, filename):
    filename = filename.replace(" ", "")
    if len(filename) > 100:
        filename = filename[:99]
    return "{0}/{1}".format(instance.itype.id, filename)

class Image(models.Model):
    stimul = models.ForeignKey("Stimul",
            on_delete=models.CASCADE, default=0 ) 
    itype = models.ForeignKey("ImageType", 
            on_delete=models.CASCADE)
    image = models.ImageField(upload_to=image_path)
    
    class Meta:
        ordering = ['itype']
        verbose_name = u"Изображение"
        verbose_name_plural = u"Изображения"
    
    def save(self, *args, **kwargs):
        try:
            this = Image.objects.get(id=self.id)
            if this.image != self.image:
                this.image.delete(save=False)
        except:
            pass
        super(Image, self).save(*args, **kwargs)

    def __str__(self):
        return self.itype.name

@receiver(pre_delete, sender=Image)
def image_delete(sender, instance, **kwargs):
    instance.image.delete(False)

class Answer(models.Model):
    pos = models.PositiveIntegerField( u"позиция",
            default=0)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=0)
    image = models.ForeignKey("Image",
            on_delete=models.CASCADE )
    stimulus = models.ForeignKey("Stimul",
            on_delete=models.CASCADE, default=0 ) 
    class Meta:
        ordering = ['stimulus','user','pos']
        verbose_name = u'Ответ'
        verbose_name_plural = u'Ответы'
    def __srt__(self):
        return "%s %s %s" % (self.stimulus, self.user, self.image)


class StimulusPassed(models.Model):    
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=0)
    stimulus = models.ForeignKey("Stimul",
            on_delete=models.CASCADE, default=0 ) 
    class Meta:
        ordering = ['stimulus','user']
        verbose_name = u'Пройденный стимул'
        verbose_name_plural = u'Пройденные стимулы'
    def __str__(self):    
        return "%s %s" % (self.stimulus, self.user)

templates/pages/index.html
{% extends 'base/base.html' %}
{% block head %}
<i class="fa fa-user-circle-o" aria-hidden="true"></i> {{user.username}}
{% endblock %}
{% block main %}
<section class="card small">
    <h2>Доступные стимулы</h2>
    <ul class="stimuli">
        {% for s in stimuli_n%}
	<li><a href="{% url 'stimulus' s.id %}">{{s.name}}</a>
        {% if request.user.is_staff %}
        <a class="excel" href="{% url 'result' s.id %}">Результат</a>
        {% endif %}    
    </li>
        {% empty %}
	<li>Вы уже пощупали все стимулы!<br/>Спасибо вам огромное! :)</li>
        {% endfor %}
    </ul>
</section>
<section class="card small">
    <h2>Пройденные стимулы</h2>
    <ul class="stimuli">
        {% for s in stimuli_p%}
	<li>{{s.name}}
        {% if request.user.is_staff %}
        <a class="excel" href="{% url 'result' s.id %}">Результат</a>
        {% endif %}
    </li>
        {% empty %}
        <li>Вы еще ничего не щупали :(</li>
        {% endfor %}
    </ul>
</section>
{% endblock %}

{% block scripts %}
<script type="text/javascript">
</script>
{% endblock %}

templates/pages/profile.html
{% extends 'base/base.html' %}
{% block head %}
<a href="{% url 'index' %}"><i class="fa fa-chevron-left" aria-hidden="true"></i> НА ГЛАВНУЮ</a> | Профиль: {{user.username}}
{% endblock %}

{% block main %}
<section class="card small profile">
    <h2>Профиль </h2>
    <form id="id_user" action="{% url 'change_user' %}">
        {% csrf_token %}
        {% for field in u_form %}
        <div>
            {{ field.errors }}
            <div>{{ field.label_tag }} {{ field }}</div>
            {% if field.help_text %}
                <p class="help">{{ field.help_text|safe }}</p>
            {% endif %}
        </div>
        {% endfor %}
    </form>
    <form id="id_userinfo" action="{% url 'change_userinfo' %}">
        {% csrf_token %}
        {% for field in ui_form %}
        <div>
            {{ field.errors }}
            <div>{{ field.label_tag }} {{ field }}</div>
            {% if field.help_text %}
                <p class="help">{{ field.help_text|safe }}</p>
            {% endif %}
        </div>
        {% endfor %}
    </form>
</section>
{% endblock %}

{% block scripts %}
    <script type="text/javascript">
    function send_data($form){
            var profile = $(".profile");
            profile.addClass('edit');
            var data = $form.serialize();
            $.ajax($form.attr('action'), {data:data, type:'POST'}).done(function(){
                profile.removeClass("edit");
            }); 
    }
    
    $(document).ready(function(){
        $('#id_user, #id_userinfo').change(function(){
            send_data($(this));
        });

    });
    </script> 
{% endblock %}

templates/pages/stimul.html
{% extends 'base/base.html' %}
{% block main %}
<h1>{{stimul.name}}</h1>
<form id="sheet">
<section class="card">
  <h2>Выберите изображение, которое вам больше нравится</h2>
  <div id="images" style="grid-template-columns:repeat({{img_count}}, 1fr)">
	  {% for image in images %}
    <div>
	    <input type="checkbox" name="{{image.id}}" id="id_{{image.id}}" value="0" required>
	    <label for="id_{{image.id}}" class="stimul"
				  style="background-image:url('{{image.image.url}}');"
		    ></label>
    </div>
    	{% empty %}
	{% endfor %}
  </div>
</section>
<section id="actions">
	<input type="button" id="reset" class="btn btn-danger" value="Сбросить выбор" />
	<input type="submit" class="btn btn-submit" value="Отправить на сервер" />
</section>
</form>
{% endblock %}

{% block scripts %}
    <script type="text/javascript">
	var count = {{img_count}};
        var p = 0;

        function clear_form(){
            var f = document.getElementByID('sheet');
            f.reset();
        }
	function reset_images(){
		$('input:checkbox:checked').prop('checked', false).prop('disabled', false).val(0);
		p = 0;
	}	
	$(document).ready(function(){
		reset_images();

		$('input[type=checkbox]').change(function(){
			if(this.checked){
				p++;
				$(this).attr('value', p);
				$(this).prop('disabled', true);
			}
		});

		$('#reset').click(function(){reset_images()});

		$( "form" ).on( "submit", function( event ) {
			  event.preventDefault();
			  var profile = $('form').serializeArray(),
			      req = {},
			      imgs = {};
			  profile.forEach(function(item, i, profile){
				req[item.name] = item.value;
			  });
			  $( ':checkbox' ).each(function(){
			  	var n = $(this).attr('name'),
				    v = $(this).attr('value');
				    imgs[n] = v;
			  });
			  req["images"] = imgs;
			  req["stimul"] = {{ stimul.id }};
			  $.ajax({
				  url: "{% url 'submit' %}",
				data:req,
				method: "POST",
			   	dataType: "json",
                          }).done(function(result){
                            if(result === 0){
                                reset_images();
                                alert('Спасибо за участие в эксперименте! Ваши данные успешно обработаны!');
                                reset_images();
                            } else if(result === 1) {
                                reset_images();
                                alert('Вы уже учавствовали в этом эксперименте!');
                            } else {
                                alert('Всё поломалось!')
                            }
                          });
		});


	});
    </script> 
{% endblock %}

templates/pages/stimulus.html
{% extends 'base/base.html' %}
{% block head %}
<a href="{% url 'index' %}"><i class="fa fa-chevron-left" aria-hidden="true"></i> НА ГЛАВНУЮ</a> | Стимул: {{stimulus.name}}
{% endblock %}

{% block main %}
<form id="sheet">
    {% csrf_token %}
<section class="card">
  <h2>Выберите изображение, которое вам больше нравится</h2>
  <div id="images">
	  {% for image in images %}
    <div>
	    <input type="checkbox" name="{{image.id}}" id="id_{{image.id}}" value="0" required>
	    <label for="id_{{image.id}}" class="stimul"
				  style="background-image:url('{{image.image.url}}');"
		    ></label>
    </div>
    	{% empty %}
	{% endfor %}
  </div>
</section>
<section id="actions">
	<input type="button" id="reset" class="btn btn-danger" value="Сбросить выбор" />
	<input type="submit" class="btn btn-submit" value="Отправить на сервер" />
</section>
</form>
{% endblock %}

{% block scripts %}
    <script type="text/javascript">
        var p = 0;

        function clear_form(){
            var f = document.getElementByID('sheet');
            f.reset();
        }
	function reset_images(){
		$('input:checkbox:checked').prop('checked', false).prop('disabled', false).val(0);
		p = 0;
	}	
	$(document).ready(function(){
		reset_images();

		$('input[type=checkbox]').change(function(){
			if(this.checked){
				p++;
				$(this).attr('value', p);
				$(this).prop('disabled', true);
			}
		});

		$('#reset').click(function(){reset_images()});

		$( "form" ).on( "submit", function( event ) {
			  event.preventDefault();
			  var req = {},
			      imgs = {};
			  $( ':checkbox' ).each(function(){
			  	var n = $(this).attr('name'),
				    v = $(this).attr('value');
				    imgs[n] = v;
			  });
			  req["images"] = imgs;
			  req["stimulus"] = {{ stimulus.id }};
			  req["csrfmiddlewaretoken"] = $('[name=csrfmiddlewaretoken]').val();
			  $.ajax({
				  url: "{% url 'submit' %}",
				data:req,
				method: "POST",
			   	dataType: "json",
                          }).done(function(result){
                            if(result === 0){
                                reset_images();
                                alert('Ваши данные успешно обработаны!');
                                window.location.href="/";
                                reset_images();
                            } else if(result === 1) {
                                reset_images();
                                alert('Вы уже учавствовали в этом эксперименте!');
                            } else {
                                alert('Всё поломалось!')
                            }
                          });
		});


	});
    </script> 
{% endblock %}